project:
  type: website

website:
  title: "Ben Ballard"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/ben-ballard-44969313/
      - icon: github
        href: https://github.com/
      - icon: medium
        href: https://medium.com/@ben.g.ballard
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
